Update run

diff --git a/run b/run
--- a/run
+++ b/run
@@ -2,10 +2,10 @@
 
 set -eu -o pipefail
 
-# this is the entrypoint for development. It wraps up compiling and calling dev.ts
-# all arguments, changes, etc. should be found in src/dev.ts
+# this is the entrypoint for development. It wraps up compiling and calling run.ts
+# all arguments, changes, etc. should be found in src/run.ts
 
-# this script checks for all the prereqs and then calls dev.ts
+# this script checks for all the prereqs and then calls run.ts
 
 export REGION_A=us-east-1
 export PROJECT=mfp
@@ -17,13 +17,13 @@ if ! which node > /dev/null ; then
 fi
 
 # check node version
-if ! diff .nvmrc <(node -v) > /dev/null ; then
-	echo "Uh Oh! The current node version does not match the version required in .nvmrc"
-	echo "If you have installed nvm, simply running 'nvm use' in this directory should solve the problem"
-	echo "If you don't have nvm yet, the instructions in the README should sort you."
-	echo "** Don't forget to add the bit to your shell profile **"
-	exit 1
-fi
+#if ! diff .nvmrc <(node -v) > /dev/null ; then
+#	echo "Uh Oh! The current node version does not match the version required in .nvmrc"
+#	echo "If you have installed nvm, simply running 'nvm use' in this directory should solve the problem"
+#	echo "If you don't have nvm yet, the instructions in the README should sort you."
+#	echo "** Don't forget to add the bit to your shell profile **"
+#	exit 1
+#fi
 
 # check yarn exists
 if ! which yarn > /dev/null ; then
@@ -40,6 +40,7 @@ fi
 
 # Parse arguments
 UPDATE_ENV=false
+LOCAL=false
 ARGS=()
 
 for arg in "$@"; do
@@ -47,27 +48,47 @@ for arg in "$@"; do
         update-env)
         UPDATE_ENV=true
         ;;
-        *)
-        ARGS+=("$arg")
+        local)
+        LOCAL=true
         ;;
     esac
+    ARGS+=("$arg")
 done
 
-# Inject secrets to .env if the flag is set
 if [ "$UPDATE_ENV" = true ]; then
-    # Check if 1Password CLI is installed
     if ! which op > /dev/null; then
-        echo "The MDCT team uses 1Password to store and retrieve development credentials. If you do not have a 1Password account please request one."
+        echo "The MDCT team uses 1Password to store and retrieve development credentials. On macOS, you can install it with 'brew install --cask 1password-cli'"
+        exit 1
+    fi
+fi
+
+if [ "$LOCAL" = true ]; then
+    if ! which docker > /dev/null ; then
+        echo "docker not found on the system. On macOS, you can install it with 'brew install docker'"
         exit 1
     fi
 
-    # call 1password vault to retrieve secrets
-    op inject -i .env.tpl -o .env -f
-    op inject -i services/ui-src/.env.tpl -o services/ui-src/.env -f
-    sed -i "" -e "s/# pragma: allowlist secret//g" .env
-    sed -i "" -e "s/# pragma: allowlist secret//g" services/ui-src/.env
+    if ! which colima > /dev/null ; then
+        echo "colima not found on the system. On macOS, you can install it with 'brew install colima'"
+        exit 1
+    fi
+
+    if ! which localstack > /dev/null ; then
+        echo "localstack not found on the system. On macOS, you can install it with 'brew install localstack/tap/localstack-cli'"
+        exit 1
+    fi
+
+    if ! colima status 2>&1 | grep -q "colima is running" ; then
+        echo "colima installed but not running. We'll start it up for you now."
+        colima start --cpu 4 --memory 10
+    fi
+
+    if ! localstack status | grep -q "running" ; then
+        echo "localstack is installed but not running. We'll start it up for you now."
+        localstack start > /dev/null 2>&1 &
+    fi
 fi
 
-# build and run dev.ts
+# build and run run.ts
 # tsc is configured to build what we expect in tsconfig.json
-./node_modules/.bin/tsc && node ./build_dev/run.js "${ARGS[@]-}"
+./node_modules/.bin/tsc && node ./build_dev/src/run.js "${ARGS[@]-}"
