Too pretty

diff --git a/run b/run
--- a/run
+++ b/run
@@ -10,37 +10,37 @@ set -eu -o pipefail
 export REGION_A=us-east-1
 
 # check node exists
-if ! which node >/dev/null; then
-    echo "node not found on the system. Install version in .nvmrc based on instructions in README"
-    exit 1
+if ! which node > /dev/null ; then
+	echo "node not found on the system. Install version in .nvmrc based on instructions in README"
+	exit 1
 fi
 
 # check node version
-if ! diff .nvmrc <(node -v) >/dev/null; then
-    echo "Uh Oh! The current node version does not match the version required in .nvmrc"
-    echo "If you have installed nvm, simply running 'nvm use' in this directory should solve the problem"
-    echo "If you don't have nvm yet, the instructions in the README should sort you."
-    echo "** Don't forget to add the bit to your shell profile **"
-    exit 1
+if ! diff .nvmrc <(node -v) > /dev/null ; then
+	echo "Uh Oh! The current node version does not match the version required in .nvmrc"
+	echo "If you have installed nvm, simply running 'nvm use' in this directory should solve the problem"
+	echo "If you don't have nvm yet, the instructions in the README should sort you."
+	echo "** Don't forget to add the bit to your shell profile **"
+	exit 1
 fi
 
 # check yarn exists
-if ! which yarn >/dev/null; then
-    echo "yarn not found on the system. On macOS, you can install it with 'brew install yarn'"
-    exit 1
+if ! which yarn > /dev/null ; then
+	echo "yarn not found on the system. On macOS, you can install it with 'brew install yarn'"
+	exit 1
 fi
 
 # check serverless is installed globally.
-if ! which serverless >/dev/null; then
-    echo "installing serverless globally"
-    yarn global add serverless
+if ! which serverless > /dev/null ; then
+	echo "installing serverless globally"
+	yarn global add serverless
 fi
 
 # have to ensure that yarn install is up to date.
 # we use .yarn_install as a marker for the last time `yarn install` was run. Rerun the command when yarn.lock is updated
 if [ "yarn.lock" -nt ".yarn_install" ]; then
-    yarn install
-    touch .yarn_install
+	yarn install
+	touch .yarn_install
 fi
 
 # Parse arguments
@@ -49,10 +49,10 @@ ARGS=()
 
 for arg in "$@"; do
     case $arg in
-    --update-env)
+        --update-env)
         UPDATE_ENV=true
         ;;
-    *)
+        *)
         ARGS+=("$arg")
         ;;
     esac
@@ -61,7 +61,7 @@ done
 # Inject secrets to .env if the flag is set
 if [ "$UPDATE_ENV" = true ]; then
     # Check if 1Password CLI is installed
-    if ! which op >/dev/null; then
+    if ! which op > /dev/null; then
         echo "The MDCT team uses 1Password to store and retrieve development credentials. If you do not have a 1Password account please request one."
         exit 1
     fi
